name: MoreTaxAddon
version: '${project.version}'
main: net.java_rin.moretaxaddon.MoreTaxAddon
api-version: '1.20'
depend:
  - Vault
  - ProtectionStones
commands:
  moretaxaddon:
    permission: moretaxaddon.command.main
    permission-message: You don't have the required permission for this command.